spring.application.name=filestorage-test

# Server Configuration
server.port=8081

# Logging Configuration
logging.level.root=INFO
logging.level.com.smeydev.filestorage=DEBUG

# MinIO Test Configuration
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=test-uploads

# Multipart upload configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
